//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERAServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~k|\"ha`RZAgezdGVO\\kJ%CV6)}6AB)t}y\\9>)S\\Rtui}rBHpy^GfwQR!ebw{SCN:L>BRk<:e?c\\z]}oCG" +
            "\'c(AI})9mv[w^k3aSHynOMg-)j0=)p[Cr-c`R\"1l\"y[[\'}pm\'#RJs1R^lK|_G\'<LqI8!iQ:Yk:X|s&g2" +
            "4R%6#$cVV{X8W(,1q\\IY\\|LqT!p4=TX]u2uq93SUg5IDT4fMCThZQP-r3(S4z%PU:jQteL-9tB1SYno&" +
            ">CShpwN{.Ek")]
        public string Secret {
            get {
                return ((string)(this["Secret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("268435456")]
        public int DataCacheLimit {
            get {
                return ((int)(this["DataCacheLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("era")]
        public string MongoDatabaseName {
            get {
                return ((string)(this["MongoDatabaseName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int SRP6Keysize {
            get {
                return ((int)(this["SRP6Keysize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tivity.org|downshare.nl|pegu.maxmaton.nl")]
        public string CustomServers {
            get {
                return ((string)(this["CustomServers"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.projectera.org")]
        public string HearbeatHostname {
            get {
                return ((string)(this["HearbeatHostname"]));
            }
            set {
                this["HearbeatHostname"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cosmopolitan")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downshare.nl")]
        public string ServerHostname {
            get {
                return ((string)(this["ServerHostname"]));
            }
            set {
                this["ServerHostname"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./Certificates/server/ssl.pfx")]
        public string RegistrationCertificate {
            get {
                return ((string)(this["RegistrationCertificate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string RegistrationCertificatePassphrase {
            get {
                return ((string)(this["RegistrationCertificatePassphrase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://pegu.maxmaton.nl/")]
        public string MongoConnectionString {
            get {
                return ((string)(this["MongoConnectionString"]));
            }
        }
    }
}
